// OVDE JE STAJALA OVERLODOVANA FUNKCIJA get_smallest
// PRE NEGO STO SMO JE KONFIGURISALI U HEADERU DA MOZE 
// DA PRIMA BILO KOJI TIP PODATKA KAO ARGUMENT
// I NA TAJ NACIN UCINILI KOD FLEKSIBILNIJIM I EFIKASNIJIM